### ISSUE TITLE
Check/unckeck measures in configuration file

### ISSUE THREAD

**Issue by msspadoni** [implydata/pivot#131]
It seems to me that the first four measures defined for a datasource went automatically checked when opening that datasource from the Pivot Home Page.
This can be inconvenient if you have a number of measures <= 4 and one of them is heavy to be executed.
There should be a way in the configuration file to instruct Pivot if a measure has to be run or not when opening related datasource.
Marco

**Comment by vogievetsky** [comment]
Good point, I though there was. Turns out there is not.

**Comment by hollow** [comment]
since upgrading to 0.8.4 (from 0.7.x) I cannot select/deselect measures anymore. A workaround is to go to "Time Series" mode, where the measurement box changes from multi select to single select. after switching back to multi select the measures can be selected even in other views where it wasn't possible previously.

maybe related to this issue?

**Comment by cybermarkus1** [comment]
its happening to me too

**Comment by evasomething** [comment]
Hi! This should have been fixed in the newest pivot (0.8.6)
