### ISSUE TITLE
Bar chart view shows incorrect data when started from 'This visualization requires at least one split' link

### ISSUE THREAD

**Issue by dclim** [implydata/pivot#157]
Repro (twitter datasource):
- From initial totals view, click on 'Totals' and select 'Bar Chart'
- When it says 'This visualization requires at least one split' click 'Add a split on Source'

You might get this:
![screen shot 2016-04-20 at 9 50 17 pm](https://cloud.githubusercontent.com/assets/11050882/14697559/2d626dea-0742-11e6-8eca-3e67e58c5df0.png)

Or maybe this (???):
![screen shot 2016-04-20 at 9 54 24 pm](https://cloud.githubusercontent.com/assets/11050882/14697583/83e07676-0742-11e6-8fae-d4a8d70a0b28.png)

This doesn't happen when you first split on Source and then change to a bar chart visualization.

**Comment by asherbitter** [comment]
I believe this is a result of sorting, rather than incorrect data. For some reason, when you select the visualization from the "this visualization requires..." screen, it sorts it by the value label by default, rather then by a measure. We are looking into it.

you can see it if you click on the split in the split bay, it will say that it is sorted by "Source".

LMK if I am wrong though.

**Comment by vogievetsky** [comment]
This is fixed in 0.8.16
