### ISSUE TITLE
Support "union" and "groupBy" datasource type

### ISSUE THREAD

**Issue by kosii** [implydata/pivot#220]
The only currently supported datasource type is "table", but it would be nice to eventually support the [two other](http://druid.io/docs/latest/querying/datasource.html) too.

**Comment by gianm** [comment]
fwiw, Druid currently (0.9.0) only supports the "query" dataSource type for "groupBy" queries, so it would probably be of limited usefulness to plywood as it does make other kinds of queries.

"union" should work though.

**Comment by vogievetsky** [comment]
As Gian said, `"union"` *should* work, I tested it and it does not, there is a small bug that is easy to fix and test for.

As for groupBy data source type that is currently out of scope for the project because it only works with the groupBy query so if you could use it you would get significantly worse performance.

I will ensure that unions work and then close this issue as groupBy data sources are "wont-fix"

**Comment by tigran-a** [comment]
Hello, 

is there any timeplan on support of union datasets? 
Thanks!
