### ISSUE TITLE
Lookups broken with Druid 0.9.1-rc3

### ISSUE THREAD

**Issue by arnaudbriche** [implydata/pivot#223]
Hi,

I'm experiencing with Druid 0.9.1-rc3 and all my lookups are broken.
Each time I choose a dimension with lookup to split or filter, I get the following message from Druid:

    {
        "error": "could not compute","message":"Could not resolve type id 'namespace' into a subtype of [simple type, class io.druid.query.lookup.LookupExtractor]\n at [Source: HttpInputOverHTTP@7944ef52; line: 1, column: 283]"
    }

Here is a dimension definition using lookup from my Pivot config file:

      - name: Campaign
        title: Campaign
        expression: $Campaign.lookup('test_mapping').fallback($Campaign)

I run Pivot version 0.8.42.

**Comment by gianm** [comment]
@arnaudbriche, lookup configurations & query syntax in 0.9.1-rc3 are not compatible with 0.9.0 due to changes in the lookup framework. The 0.9.1 final release (& some future RC as well) will likely include a compatibility layer to make migration to the new framework easier. Pivot/Plywood would support both on the query side, although you would have to migrate configs.

Some more details about the new framework are in the release notes: https://github.com/druid-io/druid/issues/2999

**Comment by vogievetsky** [comment]
Relevant tread: https://groups.google.com/forum/#!topic/druid-development/x8FQeSPvWtI (look at my post in that thread)

**Comment by arnaudbriche** [comment]
Ok, I missed this information. Thanks guys

**Comment by vogievetsky** [comment]
I am going to keep this issue open for now because I think it is helpful for anyone trying out Druid 0.9.1-rc right now. I'll close it once Pivot can actually handle the new lookups and had old lookup fallback capabilities.

**Comment by vogievetsky** [comment]
Alright. Pivot 0.9.1 released with full support for Druid 0.9.1 (the versions are a coincidence).
Please read the lookup [migration instructions](https://github.com/implydata/pivot/blob/master/docs/druid-0.9.1-lookup-migration.md).
