### ISSUE TITLE
Different granularities in time split in function of time filter

### ISSUE THREAD

**Issue by EduardHL** [implydata/pivot#226]
When you have a datasource with different query granularities (recent segments have a higher resolution; old data is rolled-up), it would be useful to show different granularities in the time split in function of the interval queried; this would avoid having jigsaw plots as the ones seen [here](https://github.com/implydata/pivot/issues/224).

I understand [current configuration options](https://github.com/implydata/pivot/blob/master/docs/configuration.md#dimensions) don't allow this.

**Comment by vogievetsky** [comment]
So just so I understand it correctly: you have mixed granularity rollup data. You want to be able to split on the lower granularity in the new data but not in the old data. So setting `granularities` to bottom out at your max (most course) granularity is not a good option for you because you are interested in the finer granularities of newer data. Is that correct?

**Comment by EduardHL** [comment]
That's exactly the use case we have.
