### ISSUE TITLE
Configurable "pinning" of dimensions

### ISSUE THREAD

**Issue by cheddar** [implydata/pivot#6]
Right now, it appears that pivot takes the top 2 dimensions from the dimensions list and "pins" them in the right pane by default.  It would be cool to be able to configure a dimension as "pinned" by default.

A suggestion for doing it is add a config param `pinned`, default it to false and if that is set to true have the dimension show up.

**Comment by vogievetsky** [comment]
+1 this is coming soon.

**Comment by vogievetsky** [comment]
This is fixed in the latest master.

Check out this commit for the new fields that you can use:

https://github.com/implydata/pivot/commit/d2cae99670d7f174adcd1b1a8e15bf1b7b8c0296

I did not go with adding `pinned` to dimensions because I realized that you might want to have them pinned in a different order than that in the list and I would not want to restrict your FREEDOM.
